In [2]:
import numpy as np
from datascience import *

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')


# Control Statements

In [3]:
x = 2
y = 3
x, y

(2, 3)

In [4]:
x > y

False

In [6]:
-x > 0

False

In [8]:
-x < 0 

True

In [9]:
x == 0

False

In [18]:
def sign(x):
    '''
    Returns "positive", "negative", "zero" depending on the value of x
    '''
    return_string = ""
    if x < 0:
        return_string = "negative"
    if x > 0:
        return_string = "positive"
    else:
        return_string = "zero"
    return return_string

SyntaxError: invalid syntax (<ipython-input-18-13caa571595a>, line 6)

In [29]:
def greater_than_number(x):
    '''
    '''
    if x > 10:
        print(x, "is greater than 10")
        
    if x > 5:
        print(x, "is greater than 5")
    else: 
        print(x, "is less than ___")

In [31]:
greater_than_number(11)

11 is greater than 10


In [32]:
sign(10), sign(-10), sign(0)

('positive', 'negative', 'zero')

### `if`, `elif`, and `else`

In [ ]:
def sign(x):
    '''
    Returns "positive", "negative", "zero" depending on the value of x
    '''

### `abs()`
Now try implementing the `abs()` function

In [33]:
help(abs)

Help on built-in function abs in module builtins:

abs(x, /)
    Return the absolute value of the argument.



In [37]:
abs(-5), abs(5), abs(0), abs(-0)

(5, 5, 0, 0)

In [45]:
def custom_abs(x):
    '''Our implementation of absoulte'''
    if x > 0:
        return x
    elif x < 0:
        return -1 * x
    else: # x == 0:
        return x

In [46]:
custom_abs(-6), custom_abs(6), custom_abs(0)

(6, 6, 0)

(back to slides)
# Random Selection

In [47]:
groups = make_array('treatment', 'control')
groups

array(['treatment', 'control'], dtype='<U9')

Let's randomly assign 1 individual to each group

In [59]:
np.random.choice(groups, 10)

array(['treatment', 'treatment', 'control', 'treatment', 'treatment',
       'treatment', 'treatment', 'control', 'treatment', 'treatment'],
      dtype='<U9')

Let's randomly assign 5 individuals to each group

In [66]:
assignments = np.random.choice(groups, 10)
assignments == 'treatment', assignments

(array([ True,  True, False, False,  True,  True,  True, False, False,
         True]),
 array(['treatment', 'treatment', 'control', 'control', 'treatment',
        'treatment', 'treatment', 'control', 'control', 'treatment'],
       dtype='<U9'))

In [69]:
Table().with_columns('assignments', assignments == 'treatment').where('assignments', True).num_rows

6

In [73]:
sum(assignments == 'treatment')

6

In [76]:
sum(make_array(True, False, False, True))

2

Let's repeat this

In [78]:
assignments = np.random.choice(groups, 10)
assignments

array(['treatment', 'treatment', 'treatment', 'treatment', 'control',
       'control', 'treatment', 'treatment', 'control', 'control'],
      dtype='<U9')

Do we see any differences?

In [79]:
assignments = np.random.choice(groups, 10)
assignments

array(['control', 'control', 'treatment', 'control', 'treatment',
       'control', 'treatment', 'control', 'control', 'control'],
      dtype='<U9')

In [81]:
np.random.choice(groups), groups

('control', array(['treatment', 'control'], dtype='<U9'))

back to slides
# Appending arrays: `np.append()`

Adding an individual to a control or treament group

In [101]:
# Make an empty array for the control and treatment groups
control_group = make_array()
treatment_group = make_array()
control_group, treatment_group
len(control_group)

0

Now let's randomly assign an individual to a group and then add the individual to the corresponding group based on the random assignment

In [96]:
groups

array(['treatment', 'control'], dtype='<U9')

In [97]:
np.append(treatment_group, 1)

array([1.])

In [100]:
#treatment_group = np.append(treatment_group, 1)
#treatment_group

array([1., 1.])

In [111]:
control_group = make_array()
treatment_group = make_array()
assigned_group =  np.random.choice(groups)
individual = "Sears Tower"
print(assigned_group)
if assigned_group == 'treatment':
    treatment_group = np.append(treatment_group, individual)
else:
    control_group = np.append(control_group, individual)

control_group, treatment_group

control


(array(['Sears Tower'], dtype='<U32'), array([], dtype=float64))

#### Let's put this control statment into a function:
- What should we name the function? 
- What are the arguments/parameters of the function?
- What should the function return?

In [114]:
def add_individual_to_group(treatment_group, control_group, individual):
    assigned_group =  np.random.choice(groups)
    print(assigned_group)
    if assigned_group == 'treatment':
        treatment_group = np.append(treatment_group, individual)
    else:
        control_group = np.append(control_group, individual)
    return treatment_group, control_group

Now let's call this function 5 times to assign 5 individuals to the different groups

In [118]:
control_group = make_array()
treatment_group = make_array()
treatment_group, control_group = add_individual_to_group(treatment_group, control_group, 0)
treatment_group, control_group

control


(array([], dtype=float64), array([0.]))

In [119]:
treatment_group, control_group = add_individual_to_group(treatment_group, control_group, 1)
treatment_group, control_group

treatment


(array([1.]), array([0.]))

In [120]:
treatment_group, control_group = add_individual_to_group(treatment_group, control_group, 2)
treatment_group, control_group

control


(array([1.]), array([0., 2.]))

In [121]:
treatment_group, control_group = add_individual_to_group(treatment_group, control_group, 3)
treatment_group, control_group

treatment


(array([1., 3.]), array([0., 2.]))

We will now see a cleaner way to assign 5 individuals to the different groups
(back to slides)
# `For` Statements

In [122]:
for i in np.arange(4):
    print('iteration', i)

iteration 0
iteration 1
iteration 2
iteration 3


In [123]:
print('iteration', 0)
print('iteration', 1)
print('iteration', 2)
print('iteration', 3)

iteration 0
iteration 1
iteration 2
iteration 3


In [125]:
for i in np.arange(1,10,2):
    print('iteration', i)

iteration 1
iteration 3
iteration 5
iteration 7
iteration 9


In [124]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

Use a `for` loop to assign the individuals to the different groups

In [128]:
treatment_group = make_array()
control_group = make_array()
#treatment_group, control_group = add_individual_to_group(treatment_group, control_group, 0)

In [130]:
for individual in np.arange(0,10):
    treatment_group, control_group = add_individual_to_group(treatment_group, control_group, individual)
treatment_group, control_group

control
control
treatment
treatment
treatment
treatment
treatment
control
treatment
treatment


(array([2., 3., 4., 5., 6., 8., 9.]), array([0., 1., 7.]))

# Heads or Tails Experiment

Let's run 10 experiments where we flip a coin 100 times and see how many times we get heads

Before we begin, let's write out all the steps we need to do

*Hint: Lets work inside out, i.e. lets first write code for one experiment*

1. make an array of heads and tails
2. flip a coin randomly (select head or tails at random) 
3. keep track of whether we got heads our tails

In [131]:
coins = make_array('heads', 'tails')
coins

array(['heads', 'tails'], dtype='<U5')

In [133]:
np.random.choice(coins, 100) 

array(['heads', 'heads', 'heads', 'heads', 'tails', 'tails', 'heads',
       'heads', 'tails', 'heads', 'tails', 'heads', 'tails', 'tails',
       'tails', 'heads', 'heads', 'heads', 'tails', 'tails', 'tails',
       'tails', 'heads', 'tails', 'heads', 'tails', 'heads', 'tails',
       'heads', 'heads', 'tails', 'tails', 'heads', 'tails', 'heads',
       'heads', 'tails', 'heads', 'heads', 'tails', 'heads', 'heads',
       'heads', 'heads', 'tails', 'heads', 'tails', 'tails', 'tails',
       'tails', 'heads', 'tails', 'heads', 'tails', 'heads', 'tails',
       'heads', 'tails', 'tails', 'tails', 'tails', 'heads', 'tails',
       'heads', 'tails', 'tails', 'heads', 'tails', 'tails', 'tails',
       'heads', 'heads', 'tails', 'tails', 'heads', 'tails', 'heads',
       'heads', 'tails', 'heads', 'heads', 'tails', 'heads', 'tails',
       'tails', 'tails', 'heads', 'heads', 'tails', 'tails', 'heads',
       'heads', 'tails', 'tails', 'tails', 'heads', 'tails', 'tails',
       'heads', 'hea

In [135]:
sum(np.random.choice(coins, 100) == 'heads')

50

In [142]:
num_heads = make_array()
for i in np.arange(1000):
    num_heads = np.append(num_heads, sum(np.random.choice(coins, 100) == 'heads'))
num_heads

array([41., 52., 45., 51., 48., 57., 48., 49., 55., 51., 60., 54., 61.,
       52., 47., 45., 51., 50., 44., 48., 47., 44., 45., 47., 43., 59.,
       52., 42., 58., 53., 42., 56., 52., 58., 57., 58., 50., 58., 54.,
       47., 47., 48., 48., 57., 50., 49., 48., 51., 46., 48., 52., 56.,
       39., 46., 48., 52., 39., 52., 53., 43., 50., 45., 47., 54., 49.,
       47., 43., 48., 44., 49., 55., 50., 53., 46., 56., 48., 45., 56.,
       46., 48., 51., 52., 42., 51., 50., 44., 51., 57., 40., 64., 53.,
       47., 60., 52., 55., 51., 53., 48., 50., 43., 48., 51., 59., 53.,
       52., 57., 44., 51., 59., 50., 51., 47., 50., 46., 46., 48., 56.,
       55., 53., 44., 60., 58., 54., 50., 62., 48., 59., 50., 42., 52.,
       51., 48., 53., 55., 57., 45., 47., 49., 55., 52., 58., 48., 57.,
       46., 57., 55., 51., 45., 50., 43., 54., 50., 53., 54., 45., 45.,
       49., 53., 52., 52., 44., 56., 48., 44., 52., 56., 48., 48., 49.,
       47., 52., 42., 57., 54., 56., 47., 49., 47., 62., 50., 49

Let's plot the results from the experiments. What type of plot should we use?

How many times did we get 40 through 60 heads? What percentage of our simulations do these represent?

In [ ]:
1. Make our coins options

(back to slides)

# Monty Hall Simulation

Lets make an array of what can be behind each door

In [40]:
goats = make_array('first goat', 'second goat')
hidden_behind_door = ... # Lets add the car

Let's make a choice. We won't choose a door but rather whats behind the door

In [45]:
# Remember np.random.choice
contestant_choice = ...
contestant_choice

'second goat'

In [ ]:
def other_goat(a_goat):
    ''' Returns the other goat that wasn't chosen
    '''
    ...
    return ...

Let's test `other_goat()`

What happens next? 
Monty chooses the door to show and we have a remaining door

In [ ]:
monty_choice = ...
remaining_door = ...

But remember, these choices are conditioned on what the contestant chose

In [ ]:
if ...: # one option for contest's choice
    ...
elif ...: # second option for contests's choice
    ...
elif ...: # third option for contestants choice
    ...
    
contestant_choice, monty_choice, remaining_door

Let's add this to a function so that we can run many simulations of the game

In [ ]:
def monty_hall():
    '''
    Simulates one run of monty hall.
    Returns values behind contestant_choice, monty_choice, remaining_door
    '''
    ...
    return 

Now let's play this game once

Let's play it another time

#### Let's play this game multiple times
How could we do that based on what we learned in today's lecture?

### Simulations

Let's make a table where we will keep simulations
We want to keep track of the original guess, what was revealed, and what is remaining in the other hidden door

In [55]:
games = Table(['Guess', 'Revealed', 'Remaining'])

### How could we see what remains for each guess?
what metho dshould we call on the table?

Let's group on the remaining to decide if we should change?

In [ ]:
# Initialize Otter
import otter
grader = otter.Notebook()
grader.export("Lecture_9_completed.ipynb", pdf=False)